# Generated by Django 5.1.1 on 2024-10-01 04:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0003_alter_customer_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("administrator", "Administrator"),
                    ("teacher", "Teacher"),
                    ("student", "Student"),
                    ("staff", "Staff"),
                ],
                max_length=15,
            ),
        ),
        migrations.DeleteModel(
            name="Customer",
        ),
    ]
