# Generated by Django 5.1.1 on 2024-10-01 05:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0007_alter_customer_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customer",
            name="student_id",
        ),
        migrations.AddField(
            model_name="customer",
            name="preferences",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.CreateModel(
            name="Business",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("business_name", models.TextField(max_length=255)),
                ("business_description", models.TextField()),
                ("business_phone_number", models.CharField(max_length=15)),
                ("address", models.CharField(max_length=255)),
                ("website_url", models.URLField(blank=True, null=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
