# Generated by Django 5.1.1 on 2024-10-03 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_delete_customer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Business',
        ),
    ]
