# Generated by Django 5.1.3 on 2024-11-17 17:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("customer", "0005_customerprofile_image"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customerprofile",
            old_name="image",
            new_name="profile_pic",
        ),
    ]
