# Generated by Django 5.1.3 on 2024-11-18 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itinerary', '0005_itinerary_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='itinerary',
            name='activity_types',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='daily_budget',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='interests',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='meal_types',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='trip_total',
            field=models.IntegerField(default=0),
        ),
    ]
