# Generated by Django 5.1.1 on 2024-10-05 20:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("activity", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="activity",
            old_name="name",
            new_name="activity_name",
        ),
    ]
