# Generated by Django 5.1.1 on 2024-10-15 20:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("activity", "0002_rename_name_activity_activity_name"),
        ("business", "0003_alter_businessprofile_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="activity",
            name="is_outdoors",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="activity",
            name="business",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="activities",
                to="business.businessprofile",
            ),
        ),
    ]
