# Generated by Django 5.1.1 on 2024-10-28 19:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("activity", "0003_activity_is_outdoors_alter_activity_business"),
    ]

    operations = [
        migrations.RenameField(
            model_name="activity",
            old_name="is_outdoors",
            new_name="indoors",
        ),
    ]
