# Generated by Django 5.1.1 on 2024-10-28 19:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("activity", "0003_alter_activity_business"),
        ("activity", "0004_rename_is_outdoors_activity_indoors"),
    ]

    operations = []
