# Generated by Django 5.1.1 on 2024-10-28 19:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("activity", "0005_merge_20241028_1939"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="activity",
            name="indoors",
        ),
    ]
