# Generated by Django 5.1.2 on 2024-11-05 18:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("activity", "0007_activity_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activity",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="activity_images/"
            ),
        ),
    ]
