# Generated by Django 5.1.2 on 2024-11-07 16:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("activity", "0008_alter_activity_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="activity",
            name="is_outdoors",
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
