# Generated by Django 5.1.2 on 2024-11-07 16:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("activity", "0009_activity_is_outdoors"),
    ]

    operations = [
        migrations.RenameField(
            model_name="activity",
            old_name="is_outdoors",
            new_name="indoors",
        ),
    ]
