# Generated by Django 5.1.2 on 2024-11-07 16:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("activity", "0010_rename_is_outdoors_activity_indoors"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="activity",
            name="indoors",
        ),
        migrations.AddField(
            model_name="activity",
            name="outdoors",
            field=models.BooleanField(default=False),
        ),
    ]
