# Generated by Django 5.1.3 on 2024-11-14 18:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("activity", "0011_remove_activity_indoors_activity_outdoors"),
    ]

    operations = [
        migrations.AddField(
            model_name="activity",
            name="category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Adventure", "Adventure"),
                    ("Relaxation", "Relaxation"),
                    ("Dining", "Dining"),
                    ("Culture", "Culture"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
