# Generated by Django 5.1.3 on 2024-12-10 20:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("activity", "0012_activity_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="activity",
            name="type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("FOOD", "Food"),
                    ("ACTIVITY", "Activity"),
                    ("ENTERTAINMENT", "Entertainment"),
                    ("TRANSPORTATION", "Transportation"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
