# Generated by Django 5.1.1 on 2024-10-24 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('day', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='day',
            old_name='Day_name',
            new_name='day_name',
        ),
    ]
