# Generated by Django 5.1.1 on 2024-10-28 19:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("day", "0002_rename_day_name_day_day_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="day",
            name="date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
