# Generated by Django 5.1.1 on 2024-10-28 19:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("day", "0003_day_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="day",
            name="date",
        ),
    ]
