# Generated by Django 5.1.1 on 2024-10-28 20:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("day", "0005_day_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="day",
            name="date",
            field=models.DateField(),
        ),
    ]
