# Generated by Django 5.1.3 on 2024-11-12 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("activity", "0011_remove_activity_indoors_activity_outdoors"),
        ("day", "0008_remove_day_day_name"),
        ("itinerary", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="day",
            name="itinerary",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="days",
                to="itinerary.itinerary",
            ),
        ),
        migrations.RemoveField(
            model_name="day",
            name="activity",
        ),
        migrations.AddField(
            model_name="day",
            name="activity",
            field=models.ManyToManyField(
                blank=True, related_name="days", to="activity.activity"
            ),
        ),
    ]
