# Generated by Django 5.1.3 on 2024-12-10 21:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("day", "0010_remove_day_activity_dayactivity"),
        ("itinerary", "0006_itinerary_activity_types_itinerary_daily_budget_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dayactivity",
            name="day",
        ),
        migrations.AddField(
            model_name="dayactivity",
            name="date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dayactivity",
            name="itinerary",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="activity",
                to="itinerary.itinerary",
            ),
        ),
    ]
