# Generated by Django 5.1.3 on 2024-11-07 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0004_alter_businessprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessprofile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='business_images/'),
        ),
    ]
