# Generated by Django 5.1.3 on 2024-11-12 22:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("business", "0005_businessprofile_image"),
    ]

    operations = [
        migrations.RenameField(
            model_name="businessprofile",
            old_name="image",
            new_name="logo",
        ),
    ]
